steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'tools'
    entrypoint: 'bash'
    args: ['create_tf_bucket.sh', '${PROJECT_ID}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'tools'
    entrypoint: 'bash'
    args: ['prepare_tf_backend.sh', '${PROJECT_ID}']

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: prepare_tfvars
    dir: "tools"
    secretEnv: ["DATADOG_API_KEY", "DATADOG_APP_KEY"] # refer to secrets ONLY in the args field of a build step.
    entrypoint: "bash"
    args:
      ['-c', 'bash prepare_tfvars.sh $LOCATION ${_ZONE_CODE1} ${_ZONE_CODE2} $$DATADOG_API_KEY $$DATADOG_APP_KEY']

  - name: 'gcr.io/migrate-legacy-java-app-gce/packer'
    dir: 'backend/config'
    args:
      - init
      - .

  - name: 'gcr.io/migrate-legacy-java-app-gce/packer'
    dir: 'backend/config'
    args:
      - build
      - -var
      - project_id=$PROJECT_ID
      - -var
      - region=$LOCATION
      - -var
      - zone_code=a
      - -var
      - xwiki_img_name=us-west1-xwiki-01t-img-$BUILD_ID
      - -var
      - img_desc=XWiki image from Packer which trigger by cloudbuild
      - -var
      - file_sources_tcp=./tcp_gcp.xml
      - -var
      - file_sources_hibernate=./hibernate_gcp.cfg.xml
      - -var
      - file_sources_startup_sh=../tools/xwiki_startup.sh
      - -var
      - deploy_sh=../tools/xwiki_manual_deploy_gcp.sh
      - .

  - name: "hashicorp/terraform"
    dir: "config"
    args:
      - init

  - name: "hashicorp/terraform"
    dir: "config"
    args:
      - apply
      - -var
      - project_id=$PROJECT_ID
      - -var
      - region=$LOCATION
      - -var
      - xwiki_img_name=us-west1-xwiki-01t-img-$BUILD_ID
      - -var
      - vm_sa_email=$PROJECT_NUMBER-compute@developer.gserviceaccount.com
      - -var-file=terraform.tfvars
      - -auto-approve

substitutions:
  _ZONE_CODE1: a
  _ZONE_CODE2: b

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATADOG_API_KEY/versions/latest
      env: "DATADOG_API_KEY"
    - versionName: projects/$PROJECT_ID/secrets/DATADOG_APP_KEY/versions/latest
      env: "DATADOG_APP_KEY"

options:
  logging: CLOUD_LOGGING_ONLY