steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'tools'
    entrypoint: 'bash'
    args: ['prepare_tf_backend.sh', '${PROJECT_ID}']

  - name: "hashicorp/terraform"
    dir: "config"
    args:
      - init

  - name: "hashicorp/terraform"
    dir: "config"
    args:
      - destroy
      - -var
      - project_id=$PROJECT_ID
      - -var
      - region=$LOCATION
      - -var
      - xwiki_img_name=us-west1-xwiki-01t-img-$BUILD_ID
      - -var
      - vm_sa_email=$PROJECT_NUMBER-compute@developer.gserviceaccount.com
      - -var-file=terraform.tfvars
      - -auto-approve

options:
  logging: CLOUD_LOGGING_ONLY
