steps:
  - name: "bash"
    id: validate_tfvars
    dir: "tools"
    entrypoint: "bash"
    args: ['validate_tfvars.sh', '${PROJECT_ID}', '${LOCATION}', '${_XWIKI_SQL_USER_PASSWORD}', '${_ZONE1}', '${_ZONE2}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'tools'
    entrypoint: 'bash'
    args: ['prepare_tf_backend.sh', '${PROJECT_ID}']

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: prepare_tfvars
    dir: "tools"
    entrypoint: "bash"
    args: ['prepare_tfvars.sh', '$LOCATION', '${_XWIKI_SQL_USER_PASSWORD}', '${_ZONE1}', '${_ZONE2}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: prepare_datadog_terraform
    dir: 'tools'
    entrypoint: 'bash'
    args: ['prepare_datadog_tf.sh', '${_DATADOG_API_KEY}', '${_DATADOG_APP_KEY}']

  - name: "hashicorp/terraform"
    dir: "infra"
    args:
      - init

  - name: "hashicorp/terraform"
    dir: "infra"
    args:
      - destroy
      - -var
      - project_id=$PROJECT_ID
      - -var
      - vm_sa_email=$PROJECT_NUMBER-compute@developer.gserviceaccount.com
      - -var-file=terraform.tfvars
      - -auto-approve

substitutions:
  _DATADOG_API_KEY: ""
  _DATADOG_APP_KEY: ""
  _XWIKI_SQL_USER_PASSWORD: "vuYTCazG0IcEc"

options:
  logging: CLOUD_LOGGING_ONLY
