steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'tools'
    entrypoint: 'bash'
    args: ['create_tf_bucket.sh', '${PROJECT_ID}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'tools'
    entrypoint: 'bash'
    args: ['prepare_tf_backend.sh', '${PROJECT_ID}']

  - name: 'gcr.io/migrate-legacy-java-app-gce/packer'
    dir: 'backend/config'
    args:
      - init
      - .

  - name: 'gcr.io/migrate-legacy-java-app-gce/packer'
    dir: 'backend/config'
    args:
      - build
      - -var
      - project_id=$PROJECT_ID
      - -var
      - region=$LOCATION
      - -var
      - zone_code=a
      - -var
      - xwiki_img_name=us-west1-xwiki-01t-img-$BUILD_ID
      - -var
      - img_desc=XWiki image from Packer which trigger by cloudbuild
      - -var
      - file_sources_tcp=./tcp_gcp.xml
      - -var
      - file_sources_hibernate=./hibernate_gcp.cfg.xml
      - -var
      - file_sources_startup_sh=../tools/xwiki_startup.sh
      - -var
      - deploy_sh=../tools/xwiki_manual_deploy_gcp.sh
      - .

  - name: "hashicorp/terraform"
    dir: "config"
    args:
      - init

  - name: "hashicorp/terraform"
    dir: "config"
    args:
      - apply
      - -var
      - project_id=$PROJECT_ID
      - -var
      - region=$LOCATION
      - -var
      - xwiki_img_name=us-west1-xwiki-01t-img-$BUILD_ID
      - -var
      - vm_sa_email=$PROJECT_NUMBER-compute@developer.gserviceaccount.com
      - -var-file=terraform.tfvars
      - -auto-approve

substitutions:
  _GCR_IMAGE: gcr.io/devops-356804/xwiki-test-mysql-nfs@sha256:08e5ac7f4cef560b9576ca89374785d335a82644708298babb73b25b1aec7d84
  _REGION: us-west1
  _ZONE_CODE1: a
  _ZONE_CODE2: b

options:
  logging: CLOUD_LOGGING_ONLY