steps:
  - name: "bash"
    id: validate_tfvars
    dir: "tools"
    entrypoint: "bash"
    args:
      [
        "validate_tfvars.sh",
        "${PROJECT_ID}",
        "${LOCATION}",
        "${_ZONE_CODE1}",
        "${_ZONE_CODE2}",
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'tools'
    entrypoint: 'bash'
    args: ['prepare_tf_backend.sh', '${PROJECT_ID}']

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: prepare_tfvars
    dir: "tools"
    entrypoint: "bash"
    args:
      ['-c', 'bash prepare_tfvars.sh $LOCATION ${_ZONE_CODE1} ${_ZONE_CODE2}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: prepare_datadog_terraform
    dir: 'tools'
    entrypoint: 'bash'
    args: [ 'prepare_datadog_tf.sh', '${_DATADOG_API_KEY}', '${_DATADOG_APP_KEY}']

  - name: "hashicorp/terraform"
    dir: "config"
    args:
      - init

  - name: "hashicorp/terraform"
    dir: "config"
    args:
      - destroy
      - -var
      - project_id=$PROJECT_ID
      - -var
      - region=$LOCATION
      - -var
      - vm_sa_email=$PROJECT_NUMBER-compute@developer.gserviceaccount.com
      - -var-file=terraform.tfvars
      - -auto-approve

substitutions:
  _DATADOG_API_KEY: ""
  _DATADOG_APP_KEY: ""

options:
  logging: CLOUD_LOGGING_ONLY
