steps:
  - name: "bash"
    id: validate_tfvars
    dir: "tools"
    entrypoint: "bash"
    args: ['validate_tfvars.sh', '${PROJECT_ID}', '${LOCATION}', '${_XWIKI_SQL_USER_PASSWORD}', '${_ZONE_CODE1}', '${_ZONE_CODE2}']

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: enable_api
    script: |
      gcloud services enable cloudresourcemanager.googleapis.com

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'tools'
    entrypoint: 'bash'
    args: ['create_tf_bucket.sh', '${PROJECT_ID}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'tools'
    entrypoint: 'bash'
    args: ['prepare_tf_backend.sh', '${PROJECT_ID}']

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: prepare_tfvars
    dir: "tools"
    entrypoint: "bash"
    args: ['prepare_tfvars.sh', '$LOCATION', '${_XWIKI_SQL_USER_PASSWORD}', '${_ZONE_CODE1}', '${_ZONE_CODE2}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: prepare_datadog_terraform
    dir: 'tools'
    entrypoint: 'bash'
    args: [ 'prepare_datadog_tf.sh', '${_DATADOG_API_KEY}', '${_DATADOG_APP_KEY}']

#  - name: 'gcr.io/migrate-legacy-java-app-gce/packer'
#    dir: 'backend/config'
#    args:
#      - init
#      - .
#
#  - name: 'gcr.io/migrate-legacy-java-app-gce/packer'
#    dir: 'backend/config'
#    args:
#      - build
#      - -var
#      - project_id=$PROJECT_ID
#      - -var
#      - region=$LOCATION
#      - -var
#      - zone_code=${_ZONE_CODE1}
#      - -var
#      - xwiki_img_name=$LOCATION-xwiki-01t-img-$BUILD_ID
#      - -var
#      - img_desc=XWiki image from Packer which trigger by cloudbuild
#      - -var
#      - file_sources_tcp=./tcp_gcp.xml
#      - -var
#      - file_sources_hibernate=./hibernate_gcp.cfg.xml
#      - -var
#      - file_sources_startup_sh=../tools/xwiki_startup.sh
#      - -var
#      - deploy_sh=../tools/xwiki_manual_deploy_gcp.sh
#      - .

  - name: "hashicorp/terraform"
    dir: "config"
    args:
      - init

  - name: "hashicorp/terraform"
    dir: "config"
    args:
      - apply
      - -var
      - project_id=$PROJECT_ID
      - -var
      - region=$LOCATION
      - -var
      - vm_sa_email=$PROJECT_NUMBER-compute@developer.gserviceaccount.com
      - -var-file=terraform.tfvars
      - -auto-approve

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: migrate_xwiki_data
    dir: "tools"
    entrypoint: "bash"
    args: ['xwiki_deploy_flavor.sh', '$LOCATION', '${_XWIKI_SQL_USER_PASSWORD}']

substitutions:
  _DATADOG_API_KEY: ""
  _DATADOG_APP_KEY: ""
  _XWIKI_SQL_USER_PASSWORD: "vuYTCazG0IcEc"

options:
  logging: CLOUD_LOGGING_ONLY